# Generated by Django 5.1.3 on 2024-12-02 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('release_date', models.DateField()),
                ('price', models.FloatField()),
                ('genre', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=100)),
                ('developer', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='games_images/')),
            ],
        ),
    ]
