# Generated by Django 5.1.3 on 2024-12-09 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0003_game_quantity_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='session_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
